### PR TITLE
fix(popover): arrow orientation on first popover opening fix

### PR DESCRIPTION
**Pull request by kostia-lev**
https://github.com/material-extended/mde/issues/28

### CODE REVIEW

**Comment by joejordanbrown** [comment]
@kostia-lev 

Thank you very much for the pull request.

I will review this tomorrow and update you, it should be merged this week :)

> For faster response try to ping me using @joejordanbrown so I receive an email notification to my inbox.

**Comment by kevinLourencoDev** [comment]
Why this was not validated ? Many people are waiting for this fix !

**Comment by joejordanbrown** [comment]
@kostia-lev @kevinLourencoDev 

Sorry about the delay. I was working on testing this before but I was then pulled back on to an emergency job and never managed to get back on to this until now.

@kostia-lev I've tested and I'm happy to merge this into master. Thanks again for the pull request 👍

**Comment by joejordanbrown** [comment]
LGTM

**Pull request merged**
