### PR TITLE
Upgrade to Angular Material beta 10

### PR DESCRIPTION
**Pull request by eyalhakim**
Adapt to breaking changes

### CODE REVIEW

**Comment by joejordanbrown** [comment]
@eyalhakim 

Thanks for the pull request.

I would have accepted this but I've only just seen it and I've already made the changes and published them. Sorry about that. 

I also made a few more changes to use the `@angular/cdk` for most of the `@angular/material` imports. I need to run a few more tests but I think I'll be able to remove `@angular/material` as a dependency soon.

**Comment by eyalhakim** [comment]
@joejordanbrown That's great! Thanks for this great library

**Comment by joejordanbrown** [comment]
@eyalhakim 

Thanks, I'm open to pull requests if you have any, it really needs refactoring at some point now the `@angular/cdk` has arrived. I would like to make a design document to decide on the final API and to give it more functionality without extended the API too much. If you have any ideas or use cases for the popover that it currently doesn't work for, let me know. I don't have any time atm to do any big changes.

Just to let you know in case you've just tried to install, I unpublished `@material-extended/mde@0.1.0-alpha.13` to bump the version because it's a breaking change.  It's now `@material-extended/mde@1.0.0-alpha.0`

**Comment by eyalhakim** [comment]
great, thanks for letting me know!

**Pull request closed without merging**
