### PR TITLE
Fix: MdePopoverTrigger in 'fullTemplateTypeCheck' mode

### PR DESCRIPTION
**Pull request by skrtheboss**
Fixed compile errors in `fullTemplateTypeCheck` mode.

Updated app dependencies.

### CODE REVIEW

**Comment by skrtheboss** [comment]
@joejordanbrown can you please have a look? Thank you.

**Comment by joejordanbrown** [comment]
@skrtheboss 

Sorry for the delay with this, I've been away.

Thank you for the pull request! 

I'll review and test this in the morning and publish the release.

**Comment by skrtheboss** [comment]
@joejordanbrown any news?

**Comment by joejordanbrown** [comment]
LGTM

**Comment by joejordanbrown** [comment]
@skrtheboss @stocksr

Sorry about the delay in accepting this pull request, I wanted to test to be sure that this fixed the issue in #25, I was unable to replicate that error on any project with `"fullTemplateTypeCheck": true`. 

I have just published this as v2.0.2 on npm, If you could confirm this has fixed the error you previously received.

**Comment by stocksr** [comment]
updated to v2.0.2 last week - no problems

**Pull request merged**
